export enum ErrorStatus {
  EmailAlreadyConfirmed = 20,
  EmailNotExists = 21,
  EmailNotConfirmed = 22,
  EmailAlreadyExists = 23,
  UsernameAlreadyExists = 30,
  UserNotFound = 33,
  ConfirmationCodeExpired = 40,
  ConfirmationCodeInvalid = 41,
  RecoveryCodeExpired = 42,
  RecoveryCodeInvalid = 43,
  ValidationError = 50,
  InvalidCredentials = 51,
  RecaptchaInvalid = 52,
  PasswordsNotMatch = 53,
  RefreshTokenInvalid = 70,
  RefreshTokenMissing = 71,
  RefreshTokenExpired = 72,
  SessionNotFound = 80,
  SessionUserMismatch = 82,
  SessionAccessForbidden = 83,
}
